# Generated by Django 3.1.2 on 2020-12-11 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe', '0005_auto_20201208_2134'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000)),
                ('description', models.TextField(verbose_name='Description')),
                ('lock', models.BooleanField(default=False, verbose_name='Lock')),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='cafe.gallery')),
                ('members', models.ManyToManyField(blank=True, related_name='community_member', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
