# Generated by Django 3.1 on 2020-12-26 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201211_2037'),
        ('cafe', '0005_auto_20201208_2134'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_auto_20201211_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('maxMember', models.PositiveIntegerField()),
                ('place', models.CharField(blank=True, max_length=2000)),
                ('gallery', models.ManyToManyField(blank=True, related_name='Event', to='cafe.Gallery')),
                ('games', models.ManyToManyField(blank=True, related_name='Event', to='game.game')),
                ('members', models.ManyToManyField(blank=True, related_name='Event_member', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_owner', to=settings.AUTH_USER_MODEL)),
                ('plays', models.ManyToManyField(blank=True, related_name='Event', to='game.play')),
            ],
        ),
    ]
