# Generated by Django 3.1.2 on 2020-12-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201211_2037'),
        ('community', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='plays',
            field=models.ManyToManyField(blank=True, null=True, related_name='Event', to='game.play'),
        ),
    ]
