# Generated by Django 3.1.2 on 2020-12-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20201226_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
