# Generated by Django 3.1.2 on 2020-12-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20201230_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='community', to='community.Event'),
        ),
    ]
