# Generated by Django 3.1.2 on 2020-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=70, verbose_name='Category')),
                ('images', models.CharField(blank=True, max_length=2000)),
                ('min_players', models.PositiveIntegerField(null=True)),
                ('max_players', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
