# Generated by Django 3.1.2 on 2020-11-27 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Category')),
                ('image', models.CharField(max_length=2000, null=True)),
                ('min_players', models.PositiveIntegerField(null=True)),
                ('max_players', models.PositiveIntegerField(null=True)),
                ('difficulty', models.FloatField(null=True)),
                ('rate', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='playmate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=200, verbose_name='Color')),
                ('starting_position', models.CharField(blank=True, max_length=200, verbose_name='Starting position')),
                ('score', models.CharField(blank=True, max_length=200, verbose_name='Score')),
                ('is_won', models.BooleanField(default=False, verbose_name='Is won')),
                ('is_first_time', models.BooleanField(default=False, verbose_name='Is first time')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='play',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semi_players', models.CharField(blank=True, max_length=2000)),
                ('date', models.DateField()),
                ('place', models.CharField(blank=True, max_length=2000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play', to='game.game')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='play', to='game.playmate')),
            ],
        ),
    ]
