# Generated by Django 3.1.2 on 2020-11-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, max_length=200, verbose_name='Category'),
        ),
    ]
