# Generated by Django 3.1 on 2020-11-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20201106_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='game',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
