# Generated by Django 3.1.2 on 2020-11-14 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_auto_20201106_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='play',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('place', models.CharField(blank=True, max_length=2000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play', to='game.game')),
                ('players', models.ManyToManyField(null=True, related_name='play', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
