# Generated by Django 3.1.2 on 2020-10-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201022_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('email',)},
        ),
    ]
