# Generated by Django 3.1 on 2020-11-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201114_1542'),
    ]

    operations = [
    ]
