# Generated by Django 3.1 on 2020-11-27 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.TextField(blank=True, verbose_name='Price')),
                ('open_time', models.TimeField(blank=True)),
                ('close_time', models.TimeField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('gallery', models.TextField(blank=True, verbose_name='Gallery')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('games', models.ManyToManyField(blank=True, related_name='Cafe', to='game.game')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cafe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
