# Generated by Django 3.1 on 2020-12-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20201127_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base64', models.TextField(blank=True, verbose_name='Base64')),
            ],
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='gallery',
        ),
        migrations.AddField(
            model_name='cafe',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='Cafe', to='cafe.Gallery'),
        ),
    ]
